---

# For full rundown of how role is created see
# http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-service.html
# Example:
# aws iam create-role --role-name "TestRole123" --assume-role-policy-document file:///path-here/ansible/roles/iam/files/EC2trustpolicydoc.json
# aws iam attach-role-policy --role-name TestRole123 --policy-arn arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
# aws iam create-instance-profile --instance-profile-name TestRole123
# aws iam add-role-to-instance-profile --instance-profile-name TestRole123 --role-name TestRole123

- name: Report roles being created
  debug: msg="Creating role {{ item.rolename }} with policydocument {{ item.policydoc }}"
  with_items:
    - "{{ IAMRoles }}"

- name: Create IAM roles
  shell: aws iam create-role --role-name "{{ item.rolename }}" --assume-role-policy-document file://"{{ role_path }}/files/{{ item.policydoc }}"
  with_items:
    - "{{ IAMRoles }}"

- name: Attach policy
  shell: aws iam attach-role-policy --role-name "{{ item.rolename }}" --policy-arn "{{ item.rolearn }}"
  with_items:
    - "{{ IAMRoles }}"

- name: Create instance profile
  shell: aws iam create-instance-profile --instance-profile-name "{{ item.rolename }}"
  with_items:
    - "{{ IAMRoles }}"

- name: Create instance profile
  shell: aws iam add-role-to-instance-profile --instance-profile-name "{{ item.rolename }}" --role-name "{{ item.rolename }}"
  with_items:
    - "{{ IAMRoles }}"