---

- name: Create VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ def_aws_region }}"
    multi_ok: false
    state: present
    tags:
      Name: "{{ vpc_name }}"
      environment: "{{ env_name }}"
  register: rtn_vpc

- name: Debug VPC creation
  debug: msg="VPC created with ID {{ rtn_vpc.vpc.id }}"

- name: Create subnets
  ec2_vpc_subnet:
    region: "{{ def_aws_region }}"
    state: present
    vpc_id: "{{ rtn_vpc.vpc.id }}"
    az: "{{ item.value.az }}"
    cidr: "{{ item.value.cidr }}"
    tags:
      Name: "{{ item.value.name }}"
      environment: "{{ env_name }}"
      access: "{{ item.value.access }}"
  with_dict: "{{ vpc_subnets }}"
  register: rtn_subnets

- name: Debug subnet creation
  debug: msg="{{ item.subnet.tags.access }} subnet {{ item.subnet.cidr_block }} created with ID {{ item.subnet.id }} and tags {{ item.subnet.tags }}"
  with_items: "{{ rtn_subnets.results }}"

- name: Concatenate public subnet list
  set_fact:
    public_subnets: []

- name: Concatenate public subnet list
  set_fact:
    public_subnets: "{{ public_subnets + [ item.subnet.id ] }}"
  when: item.subnet.tags.access == "public"
  with_items: "{{ rtn_subnets.results }}"

- name: Report public subnets
  debug: msg="Public subnets are {{ public_subnets }}"

- name: Conc2
  debug: msg="Public subnets are {{ rtn_subnets.results | selectattr('subnet.tags.access', 'equalto', 'public') | map(attribute='subnet.id') | join(',') }}"

- name: Create IGW
  ec2_vpc_igw:
    region: "{{ def_aws_region }}"
    vpc_id: "{{ rtn_vpc.vpc.id }}"
    state: present
    tags:
      Name: "{{ vpc_name }}-IGW"
      environment: "{{ env_name }}"
  register: rtn_igw

- name: Debug IGW creation
  debug: msg="IGW created with ID {{ rtn_igw.gateway_id }} and tags {{ rtn_igw.tags }}"

- name: Set up public subnet route table
  ec2_vpc_route_table:
    vpc_id: "{{ rtn_vpc.vpc.id }}"
    region: "{{ def_aws_region }}"
    tags:
      Name: "{{ vpc_name }}-PublicRTBL"
      environment: "{{ env_name }}"
    subnets:
      - "{{ item }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ rtn_igw.gateway_id }}"
    with_items:
      - "{{ public_subnets }}"
#  register: rtn_public_rtbl
