---

- name: Create VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ def_aws_region }}"
    multi_ok: false
    state: present
    tags:
      environment: "{{ env_name }}"
  register: rtn_vpc

- name: Debug VPC creation
  debug: msg="VPC created with ID {{ rtn_vpc.vpc.id }}"

- name: Create subnets
  ec2_vpc_subnet:
    region: "{{ def_aws_region }}"
    state: present
    vpc_id: "{{ rtn_vpc.vpc.id }}"
    az: "{{ item.value.az }}"
    cidr: "{{ item.value.cidr }}"
    tags:
      environment: "{{ env_name }}"
  with_dict: "{{ vpc_subnets }}"
  register: rtn_subnets

- name: Debug subnet creation
  debug: msg="Subnets created with ID {{ rtn_subnets }}"

- name: Create IGW
  ec2_vpc_igw:
    region: "{{ def_aws_region }}"
    vpc_id: "{{ rtn_vpc.vpc.id }}"
    state: present
    tags:
      environment: "{{ env_name }}"
  register: rtn_igw

- name: Debug IGW creation
  debug: msg="IGW created with ID {{ rtn_igw.gateway_id }} and tags {{ rtn_igw.tags }}"

#- name: Set up public subnet route table
#  ec2_vpc_route_table:
#    vpc_id: "{{ rtn_vpc.vpc.id }}"
#    region: "{{ def_aws_region }}"
#    tags:
#      environment: "{{ env_name }}"
#    subnets:
#      - "{{ jumpbox_subnet.subnet.id }}"
#      - "{{ frontend_subnet.subnet.id }}"
#      - "{{ vpn_subnet.subnet_id }}"
#    routes:
#      - dest: 0.0.0.0/0
#        gateway_id: "{{ igw.gateway_id }}"
#  register: public_route_table
