- hosts: localhost
  connection: local
  gather_facts: False

  roles:
    - { role: vpc, action: add }

  tasks:
    - name: Start
      ec2:
        region: "{{ aws_region }}"
        zone: "{{ aws_zone }}"
        state: stopped
        instance_tags:
          class: web1
          class: db
