- hosts: localhost
  connection: local
  gather_facts: False

  roles:
    - vpc

  tasks:
    - name: Start
      ec2:
        region: "{{ def_aws_region }}"
        zone: "{{ def_aws_zone }}"
        state: stopped
        instance_tags:
          class: web1
          class: db
